Corrige typos en el bloque 1, temas 1 y 2
Fictizia/Master-en-Programacion-con-Python_ed1 pull request #24
Opened 2019-03-29 17:42 UTC by y4izus

He visto algunos typos y los he corregido ya que dijimos que sería más rápido que ir haciendo issues. El texto se ha formateado y parece que he cambiado todo, pero no es así

2019-04-02 09:10 UTC, delapuente requested changes
Muchas gracias por las ediciones. ¿Podrías decirme que editor o plugin has utilizado para editar el markdown? En general me gusta más este formato y me gustaría aplicarlo a todas partes.

2019-04-02 09:10 UTC, delapuente commented on teoria/b01t01.md
> +> Although never is often better than _right_ now.
Preferiría conservar este formato puesto que es así como se muestra en el Zen de Python.

2019-04-02 09:10 UTC, delapuente commented on teoria/b01t02.md
> +3)  Cambia la shell de tu usuario a zsh.
```suggestion
3.  Cambia la shell de tu usuario a zsh.
```

2019-04-03 16:56 UTC, y4izus commented on teoria/b01t01.md
> +> Although never is often better than _right_ now.
Esto no lo toqué... sinceramente, no sé cómo se ha cambiado, lo siento

2019-04-03 19:36 UTC, y4izus commented on teoria/b01t02.md
> +3)  Cambia la shell de tu usuario a zsh.
He usado el VSCode, sin plugins para markdown

2019-04-08 10:06 UTC, delapuente approved these changes

2019-04-08 10:06 UTC, merged