Amplía de decoradores a decoradores parametrizados
Fictizia/Master-en-Programacion-con-Python_ed1 pull request #34
Opened 2019-04-12 10:55 UTC by y4izus

Reimplementa `log`, `log_parameters` y `log_return` como decoradores parametrizados de manera que se obtiene el mismo resultado que con el `log` parametrizado

2019-04-12 15:21 UTC, delapuente requested changes

2019-04-12 15:21 UTC, delapuente commented on alumni/y4izus/param_decorators.py
> +        def _decorated(*args, **kwargs):
Usa `wraps` aquí para decir que esta función decora `target`.

2019-04-12 15:21 UTC, delapuente commented on alumni/y4izus/param_decorators.py
> +    return (b + root) / 2 * a, (b - root) / 2 * a
Es `-b` en ambos elementos de la tupla, fallo mío.

2019-04-24 07:14 UTC, delapuente requested changes

2019-04-24 07:14 UTC, delapuente commented on alumni/y4izus/param_decorators.py
> +        def _decorated(*args, **kwargs):
Te falta usar `wraps` aquí.

2019-04-26 10:42 UTC, y4izus commented on alumni/y4izus/param_decorators.py
> +        def _decorated(*args, **kwargs):
Añadido :)

2019-04-27 08:19 UTC, merged